---
abstract: 'IPC::Open3-like interface providing shell-style pipelines in Perl'
author:
  - 'Erin Schönhals erin@cpanel.net>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Pipeline
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.5
