---
abstract: 'IPC::Open3-like interface providing shell-style pipelines in Perl'
author:
  - 'Erin Schoenhals <erin@cpanel.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Pipeline
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.008000
version: 0.9
